SportPosition.create(sport: "NBA", name: "PG", display_priority: 1)
SportPosition.create(sport: "NBA", name: "SG", display_priority: 2)
SportPosition.create(sport: "NBA", name: "SF", display_priority: 3)
SportPosition.create(sport: "NBA", name: "PF", display_priority: 4)
SportPosition.create(sport: "NBA", name: "C", display_priority: 5)
SportPosition.create(sport: "NBA", name: "UTIL", display_priority: 0, visible: false)

LineupSpotProto.create(sport: "NBA", sport_position_name: "PG", spot: 0)
LineupSpotProto.create(sport: "NBA", sport_position_name: "PG", spot: 1)
LineupSpotProto.create(sport: "NBA", sport_position_name: "SG", spot: 2)
LineupSpotProto.create(sport: "NBA", sport_position_name: "SG", spot: 3)
LineupSpotProto.create(sport: "NBA", sport_position_name: "SF", spot: 4)
LineupSpotProto.create(sport: "NBA", sport_position_name: "SF", spot: 5)
LineupSpotProto.create(sport: "NBA", sport_position_name: "PF", spot: 6)
LineupSpotProto.create(sport: "NBA", sport_position_name: "PF", spot: 7)
LineupSpotProto.create(sport: "NBA", sport_position_name: "C", spot: 8)
LineupSpotProto.create(sport: "NBA", sport_position_name: "UTIL", spot: 9)
