# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
  login: &login
    adapter: postgresql
    username: Lungs
    password: 
    host: localhost
    port: 5432
    pool: 5
    timeout: 5000

  development:
    <<: *login
    database: fantasycapital_dev
  production:
    <<: *login
    database: fantasycapital
  test:
    <<: *login
    database: fantasycapital_test
