require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WaitingListsController do

  # This should return the minimal set of attributes required to create a valid
  # WaitingList. As you add validations to WaitingList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WaitingListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all waiting_lists as @waiting_lists" do
      waiting_list = WaitingList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:waiting_lists).should eq([waiting_list])
    end
  end

  describe "GET show" do
    it "assigns the requested waiting_list as @waiting_list" do
      waiting_list = WaitingList.create! valid_attributes
      get :show, {:id => waiting_list.to_param}, valid_session
      assigns(:waiting_list).should eq(waiting_list)
    end
  end

  describe "GET new" do
    it "assigns a new waiting_list as @waiting_list" do
      get :new, {}, valid_session
      assigns(:waiting_list).should be_a_new(WaitingList)
    end
  end

  describe "GET edit" do
    it "assigns the requested waiting_list as @waiting_list" do
      waiting_list = WaitingList.create! valid_attributes
      get :edit, {:id => waiting_list.to_param}, valid_session
      assigns(:waiting_list).should eq(waiting_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WaitingList" do
        expect {
          post :create, {:waiting_list => valid_attributes}, valid_session
        }.to change(WaitingList, :count).by(1)
      end

      it "assigns a newly created waiting_list as @waiting_list" do
        post :create, {:waiting_list => valid_attributes}, valid_session
        assigns(:waiting_list).should be_a(WaitingList)
        assigns(:waiting_list).should be_persisted
      end

      it "redirects to the created waiting_list" do
        post :create, {:waiting_list => valid_attributes}, valid_session
        response.should redirect_to(WaitingList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved waiting_list as @waiting_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        WaitingList.any_instance.stub(:save).and_return(false)
        post :create, {:waiting_list => { "email" => "invalid value" }}, valid_session
        assigns(:waiting_list).should be_a_new(WaitingList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WaitingList.any_instance.stub(:save).and_return(false)
        post :create, {:waiting_list => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested waiting_list" do
        waiting_list = WaitingList.create! valid_attributes
        # Assuming there are no other waiting_lists in the database, this
        # specifies that the WaitingList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WaitingList.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => waiting_list.to_param, :waiting_list => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested waiting_list as @waiting_list" do
        waiting_list = WaitingList.create! valid_attributes
        put :update, {:id => waiting_list.to_param, :waiting_list => valid_attributes}, valid_session
        assigns(:waiting_list).should eq(waiting_list)
      end

      it "redirects to the waiting_list" do
        waiting_list = WaitingList.create! valid_attributes
        put :update, {:id => waiting_list.to_param, :waiting_list => valid_attributes}, valid_session
        response.should redirect_to(waiting_list)
      end
    end

    describe "with invalid params" do
      it "assigns the waiting_list as @waiting_list" do
        waiting_list = WaitingList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WaitingList.any_instance.stub(:save).and_return(false)
        put :update, {:id => waiting_list.to_param, :waiting_list => { "email" => "invalid value" }}, valid_session
        assigns(:waiting_list).should eq(waiting_list)
      end

      it "re-renders the 'edit' template" do
        waiting_list = WaitingList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WaitingList.any_instance.stub(:save).and_return(false)
        put :update, {:id => waiting_list.to_param, :waiting_list => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested waiting_list" do
      waiting_list = WaitingList.create! valid_attributes
      expect {
        delete :destroy, {:id => waiting_list.to_param}, valid_session
      }.to change(WaitingList, :count).by(-1)
    end

    it "redirects to the waiting_lists list" do
      waiting_list = WaitingList.create! valid_attributes
      delete :destroy, {:id => waiting_list.to_param}, valid_session
      response.should redirect_to(waiting_lists_url)
    end
  end

end
